import type { Metadata } from "next";
import { signOut } from "./login/actions";
import "styles/globals.css";
import { createClient } from "@/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body>
        {user && (
          <div className="flex items-center justify-between w-full p-10">
            <h2 className="text-3xl font-semibold text-center flex-1">
              QR File Share
            </h2>
            <button
              className="ml-auto px-2 py-1 bg-black text-white font-medium rounded-lg shadow-md hover:bg-gray-500 transition duration-300"
              onClick={signOut}
            >
              Log Out
            </button>
          </div>
        )}

        {children}
      </body>
    </html>
  );
}
